version: '2.1'
services:
  server:
    container_name: clique-api-server
    build: .
    command: npm start
    depends_on:
      - postgres
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"

  postgres:
    container_name: clique-api-postgres
    image: postgres:9.6.2-alpine
    restart: always
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
     - "5432:5432"

  redis:
    container_name: clique-api-redis
    image: redis:4.0.8-alpine
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    sysctls:
      - net.core.somaxconn=65535

volumes:
  postgres-data:
  redis-data:
