version: '2'

services:
  server:
    container_name: clique-graphql-server
    build: .
    command: yarn run prod
    restart: always
    env_file: .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
